node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; */

        app = docker.build("apachedocker/apacheub", "./apachedocker") 
    }

    stage('Test image') {
        
        app.inside {
            sh 'pwd;ls -lrt'
        }
    }

    }
