node {
    def app

    stage('Clone repository') {
        /* Let's make sure we have the repository cloned to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* This builds the actual image; */

        app = docker.build("javadocker" , "./javadocker" )
    }

    stage('Push image') {
    /* Push Image to ECR; */
  docker.withRegistry('https://431226684774.dkr.ecr.eu-west-1.amazonaws.com', 'ecr:eu-west-1:ECR-docker') 
        {
           app.push("${env.BUILD_NUMBER}")  
            app.push("latest")
          }
    }

}
